linters:
  enable-all: true
  disable:
    - ifshort
    - wsl
    - lll
    - godox
    - funlen
    - nlreturn
    - gofumpt
    - scopelint
    - gocognit
    - gomnd
    - dupl
    - tagliatelle
    - goconst
    - gocyclo
    - testpackage
    - nestif
    - gci
    - gochecknoglobals
    - maintidx
    - nosnakecase
    - containedctx
    - godot
  fast: true
output:
  format: github-actions