name: lint
on: [push]
jobs:
  build:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: lint
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_GO: true
          VALIDATE_ALL_CODEBASE: false
          USE_FIND_ALGORITHM: true
