name: lint
on: [push]
jobs:
  build:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          skip-cache: true
