name: lint
on:
  pull_request:
      branches: [master]
jobs:
  build:
    name: go-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
